apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: nodered
  name: nodered-data
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: storage-account-v2
  resources:
    requests:
      storage: 30Gi
